baseURL = "https://tequenikality.net/"
languageCode = "en-gb"
defaultContentLanguage = "en"
title = "Tequenikality"
theme = "hermit"
pygmentsCodefences  = true
pygmentsUseClasses  = true
rssLimit = 75
copyright = "Copyright (c) 2020 - Brandon Powell - All Rights Reserved"
enableEmoji = true
#googleAnalytics = "G-C8VPGCNJHN"
[author]
  name = "Brandon Powell"
[taxonomies]
  tag = "tags"
  # Categories are disabled by default.
[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "02-01-2006"
  dateformNumTime = "02-01-2006 15:04 +0000"
  description = "Just a place for me to share my thoughts and socialise"
  # images = [""]
  themeColor = "#494f5c"
  homeSubtitle = "Doing Things Differently."
  footerCopyright = ' - All Rights Reserved'
  justifyContent = true
  relatedPosts = true
  code_copy_button = true
  customCSS = ["/custom.css"]
  [[params.social]]
    name = "facebook"
    url = "https://facebook.com/Tequenikality"
  [[params.social]]
    name = "email"
    url = "mailto:contact@tequenikality.net"
  [[params.social]]
    name = "github"
    url = "https://github.com/Tequenikality"
[menu]
  [[menu.main]]
    name = "Projects"
    url = "projects/"
    weight = 50
  [[menu.main]]
    name = "Store"
    url = "https://store.tequenikality.net"
    weight = 40
  [[menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 30
  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 20
  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 10
